seed_everything: 42
model:
  class_path: rave.model.RAVE
  init_args:
    data_size: 16
    capacity: 64 # 32 for small
    latent_size: 256
    ratios: [4, 4, 2, 2, 2] # small: [4, 4, 4, 2], large: [4, 4, 2, 2, 2]
    bias: true 
    loud_stride: 1
    use_noise: true
    noise_ratios: [4, 4, 4]
    noise_bands: 5
    d_capacity: 16
    d_multiplier: 4
    d_n_layers: 4
    warmup: 300000  # large=3000000
    mode: "hinge"
    no_latency: false
    sr: 44100
    min_kl: 0.1
    max_kl: 0.3
    cropped_latent_size: 0
    feature_match: true

# ------------------ Datasets ------------------       
data:
  class_path: data.vocals.VocalsDataModule
  init_args:
    
    dataset_dirs: 
      - "/media/data/bernardo/tencys_vocals_mono_16b_trim/"
      - "/media/data/bernardo/dataset3_ghero_vocals_mono_16b_trim/"
      - "/media/data/bernardo/dataset4_ghero_vocals_mono_16b_trim/"
      # - "/home/bernardo/data/tencys_vocals_mono_16b_trim_unknown/"

# ------------------ Data loading hyperparameters ------------------       
    batch_size: 50
    batch_size_val:  32
    nr_samples: 65536
    normalize: true
    num_workers: 40
    batch_sampling_mode: "sample_clips" # or sample groups
    eval_frac: 0.06
    verbose: true
    use_random_loader: false
    group_name_is_folder: true
    group_by_artist: true
    sr: 44100  # check, declared 2 times

# ------------------ Augmentations ------------------       
    augs: 
      "enable": true
      "gaussian_noise": 0
      "pitch_shift_naive": 0
      "time_stretch": 0
      "gain": 0.5
      "shift": 0
      "parametric_eq": 0.3
      "tanh_distortion": 0
      "time_mask": 0.5
      "formant_shift_parselmouth": 0
      "pitch_shift_parselmouth": 1.2
      "pitch_range_parselmouth": 1.2
      "pitch_shift_parselmouth_prob": 0.5
      "random_phase_mangle": 0.8

# ------------------ Training ------------------
trainer:
  gpus: 2 # check
  max_epochs: 100000
  max_steps: 5000000
  # val_check_interval: 500
  accelerator: "ddp"
  check_val_every_n_epoch: 10
  # ckpt: None

# ------------------ Logger ------------------
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: "runs/test2_vocals_44100"
      name: "rave"
      # version: 4  # IMPORTANT TO SET

# ------------------ Checkpoint callbacks ------------------
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: "validation"
        mode: "min"
        filename: "best-val-{epoch}-{step}"
        save_top_k: 2

    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        filename: "last"
        save_top_k: 1

    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        every_n_epochs: 25
        save_top_k: -1
        filename: "cptk-{epoch}-{step}"
    - class_path: callbacks.visualization.PlotSpectograms
      init_args:
        log_n_epochs: 20
        n_to_log: 2
        save_png: true
        randomize: true
        log_audio: true

    # - class_path: callbacks.log_audio.LogAudio
    #     init_args:
    #       log_n_epochs: 50