seed_everything: 42
model:
  class_path: rave.model.RAVE
  init_args:
    data_size: 16
    capacity: 64 # 32 for small
    latent_size: 128
    ratios: [4, 4, 2, 2, 2] # small: [4, 4, 4, 2], large: [4, 4, 2, 2, 2]
    bias: true 
    loud_stride: 1
    use_noise: true
    noise_ratios: [4, 4, 4]
    noise_bands: 5
    d_capacity: 16
    d_multiplier: 4
    d_n_layers: 4
    warmup: 1500000  # large=3000000
    mode: "hinge"
    no_latency: false
    sr: 48000
    min_kl: 0.1
    max_kl: 0.2
    cropped_latent_size: 0
    feature_match: true

# ------------------ Datasets ------------------       
data:
  class_path: data.vctk.VCTKDataModule
  init_args:
    
    dataset_dirs: 
      - "/home/bernardo/data/wav48_silence_trimmed"

# ------------------ Data loading hyperparameters ------------------       
    batch_size: 64
    batch_size_val:  16
    nr_samples: 65536
    normalize: true
    num_workers: 40
    batch_sampling_mode: "sample_clips" # or sample groups
    eval_frac: 0.06
    verbose: true
    use_random_loader: false
    group_name_is_folder: true
    group_by_artist: true
    sr: 48000  # check, declared 2 times

# ------------------ Training ------------------
trainer:
  gpus: -1 # check
  max_epochs: 100000
  max_steps: 3000000
  val_check_interval: 500
  # accelerator: "dp"
  # check_val_every_n_epoch: 
  # ckpt: None

# ------------------ Logger ------------------
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: "runs/test_config"
      name: "rave"

# ------------------ Checkpoint callbacks ------------------
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        #dirpath: ""
        monitor: "validation"
        mode: "min"
        filename: "best-{epoch}-{step}"
    # - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    #   init_args:
    #     every_n_epochs: 20
    #     filename: "best-{epoch}-{step}"
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        filename: "last"